site_name: "mobile-developer-guide"
site_description: "A guide to mobile application development for the Government of the Province of British Columbia"

nav:
  - Introduction: index.md
  - Getting Started: getting_started.md
  - Distribution Methods: distribution_methods.md
  - Apple App Signing: apple_app_signing.md
  - App Store Connect API Key: app_store_connect_api_key.md
  - Google App Signing: google_app_signing.md
  - Google Signing For React Native Apps: google_react_native_signing.md
plugins:
  - techdocs-core