site_name: "mobile-developer-guide"
site_description: "A guide to mobile application development for the Government of the Province of British Columbia"
repo_url: https://github.com/bcgov/mobile-developer-guide
edit_uri: edit/main/docs/

nav:
  - Introduction: index.md
  - Getting Started: getting_started.md
  - Distribution Methods: distribution_methods.md
  - App Management: app_management.md
  - Apple App Signing: apple_app_signing.md
  - Google App Signing: google_app_signing.md
  - Google Signing For React Native Apps: google_react_native_signing.md
  - Publish your app: publish.md
plugins:
  - techdocs-core